import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportFailuresToPDF(
  failures,
  singleFailure = null
) {
  if (
  !singleFailure &&
  failures.length === 0
) {
  alert("No data available to export.");
  return;
}

  const doc = new jsPDF();

  doc.setFontSize(20);

  doc.text(
     singleFailure
    ? "Failure Report"
    : "Failure Journal Report",
  14,
  20
);

  doc.setFontSize(11);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    30
  );

  if (singleFailure) {

  let y = 40;

   const addSection = (title, value) => {

  if (!value) return;

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(13);
  doc.setFont(undefined, "bold");

  if (y > pageHeight - 30) {
    doc.addPage();
    y = 20;
  }

  doc.text(title, 14, y);

  y += 7;

  doc.setFont(undefined, "normal");
  doc.setFontSize(11);

  const lines =
    doc.splitTextToSize(
      String(value),
      180
    );

  if (
    y + lines.length * 6 >
    pageHeight - 20
  ) {

    doc.addPage();

    y = 20;

  }

  doc.text(lines, 14, y);

  y +=
    lines.length * 6 + 8;

};


  const addListSection = (
title,
items
) => {

if (!items?.length) return;

const pageHeight =
doc.internal.pageSize.height;

doc.setFontSize(13);

doc.setFont(undefined,"bold");

if (y > pageHeight-30){

doc.addPage();

y=20;

}

doc.text(title,14,y);

y+=8;

doc.setFont(undefined,"normal");

doc.setFontSize(11);

items.forEach(item=>{

const lines=
doc.splitTextToSize(
`• ${item}`,
175
);

if(
y+lines.length*6>
pageHeight-20
){

doc.addPage();

y=20;

}

doc.text(lines,18,y);

y+=lines.length*6+3;

});

y+=5;

};



  addSection("Title", singleFailure.title);

  addSection("Description", singleFailure.description);

  addSection("Mood", singleFailure.mood);

  addSection("Lesson Learned", singleFailure.lesson);

  addSection("Action Plan", singleFailure.actionPlan);

  addSection(
    "Status",
    singleFailure.status
  );

  addSection(
    "Progress",
    `${singleFailure.progress}%`
  );

  if (singleFailure.targetDate) {

    addSection(
      "Target Date",
      new Date(
        singleFailure.targetDate
      ).toLocaleDateString()
    );

  }

  if (singleFailure.successStory) {

    addSection(
      "Success Story",
      singleFailure.successStory
    );

  }

  // =======================
  // AI INSIGHTS
  // =======================

  if (
    singleFailure.aiInsights &&
    singleFailure.aiInsights.rootCause
  ) {

    doc.setFontSize(16);
    doc.setFont(undefined, "bold");

    doc.text(
      "AI Mentor Insights",
      14,
      y
    );

    y += 10;

    addSection(
      "Root Cause",
      singleFailure.aiInsights.rootCause
    );

    addListSection(
      "Strengths",
      singleFailure.aiInsights.strengths
     );

    addListSection(
       "Improvement Plan",
        singleFailure.aiInsights.improvementPlan
      );

    addSection(
      "Estimated Recovery",
      `${singleFailure.aiInsights.estimatedRecoveryDays} Days`
    );

    addSection(
      "Biggest Risk",
      singleFailure.aiInsights.biggestRisk
    );

    addListSection(
      "Recommended Topics",
        singleFailure.aiInsights.recommendedTopics
    );

    addSection(
      "Motivation",
      singleFailure.aiInsights.motivation
    );

  }

}

  if (!singleFailure) {

  const tableData = failures.map((item) => [
    item.title,
    item.mood,
    item.status,
    `${item.progress}%`,
    item.targetDate
      ? new Date(item.targetDate).toLocaleDateString()
      : "-",
  ]);

  autoTable(doc, {
    startY: 40,
    head: [[
      "Title",
      "Mood",
      "Status",
      "Progress",
      "Target Date",
    ]],
    body: tableData,
  });

  doc.setFontSize(10);

doc.setTextColor(120);

doc.text(
  "Generated by Failure Journal AI",
  14,
  285
);

}

      doc.setFontSize(10);

      doc.setTextColor(120);

doc.text(

"Generated by Failure Journal AI",

14,

doc.internal.pageSize.height-10

);




  doc.save("failure-journal.pdf");
}